"""Module: engineering
Purpose: Generate technical features with strict PIT compliance (shift=1)."""

import pandas as pd
import numpy as np

class FeatureEngineer:
    """
    Generates technical indicators and statistical features for financial time series.
    Enforces strict Point-In-Time (PIT) compliance by shifting features that use current close.
    """

    def __init__(self, use_technical_indicator: bool = True,
                 use_turbulence: bool = False,
                 user_defined_feature: bool = False):
        self.use_technical_indicator = use_technical_indicator
        self.use_turbulence = use_turbulence
        self.user_defined_feature = user_defined_feature

    def preprocess_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Main method to generate features.
        Assumes df has columns: date, tic, open, high, low, close, volume
        """
        df = df.copy()
        df = df.sort_values(['tic', 'date'])
        
        # 1. Log Returns
        # We calculate return from t-1 to t. This is known at time t.
        # However, for trading at Open of t+1, we can use data up to Close of t.
        # So raw features at t are fine, provided we execute at t+1 Open.
        # If we execute at t Close, we can't use t Close to decide. 
        # FinRL standard is often execution at t+1 Open or t Close.
        # Phase 0 specs say "next-bar open execution", so features using Close_t are valid for Action_t.
        # BUT, standard practice for safety is often to shift(1) everything to be absolutely sure.
        # The requirement says "rolling z-score on Close (and Volume) with shift(1)".
        
        # Calculate returns first
        df['log_return'] = df.groupby('tic')['close'].apply(lambda x: np.log(x / x.shift(1)))
        
        # 2. Rolling Z-Score on Close (Price)
        # (Close - Mean) / Std
        # Window size 20 (approx 1 month)
        window = 20
        df['close_rolling_mean'] = df.groupby('tic')['close'].transform(lambda x: x.rolling(window=window).mean())
        df['close_rolling_std'] = df.groupby('tic')['close'].transform(lambda x: x.rolling(window=window).std())
        df['close_zscore'] = (df['close'] - df['close_rolling_mean']) / df['close_rolling_std']
        
        # 3. Rolling Z-Score on Volume
        df['volume_rolling_mean'] = df.groupby('tic')['volume'].transform(lambda x: x.rolling(window=window).mean())
        df['volume_rolling_std'] = df.groupby('tic')['volume'].transform(lambda x: x.rolling(window=window).std())
        df['volume_zscore'] = (df['volume'] - df['volume_rolling_mean']) / df['volume_rolling_std']
        
        # 4. Apply shift(1) to enforced features
        # This effectively makes the feature at time t equal to the value from t-1.
        # This is extremely conservative but safe.
        # Note: 'log_return' at t is ln(P_t / P_{t-1}). Shifting it means at t we see ln(P_{t-1}/P_{t-2}).
        # The Phase 0 spec explicitly asks for "rolling z-score ... with shift(1)".
        
        features_to_shift = ['close_zscore', 'volume_zscore', 'log_return']
        
        for feat in features_to_shift:
            df[f'{feat}_shifted'] = df.groupby('tic')[feat].shift(1)
            
        # Clean up intermediate columns if needed, or keep them.
        # We will drop NaNs generated by rolling windows and shifts.
        df = df.dropna()
        
        return df.reset_index(drop=True)
