"""
Create a simpler notebook with combined Download + Feature Engineering in one cell.
"""
import json

notebook_path = "colab_phase10_synapse.ipynb"

# Create a cleaner, more robust notebook
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Phase 10: Synapse Arbitrator Validation\n",
                "Walk-Forward Testing (2020-2024) on Google Colab\n",
                "\n",
                "**Run all cells in order (Runtime > Run all)**"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 1: Setup\n",
                "!pip install -q --upgrade yfinance stockstats\n",
                "!pip install -q torch pandas numpy scipy\n",
                "\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import yfinance as yf\n",
                "import torch\n",
                "import torch.nn as nn\n",
                "from scipy.special import softmax\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n",
                "\n",
                "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
                "print(f\"✓ Setup complete. Device: {device}, yfinance: {yf.__version__}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 2: Configuration\n",
                "TICKERS = [\"AAPL\", \"MSFT\", \"GOOGL\", \"AMZN\", \"META\", \"NVDA\", \"JPM\", \"V\", \"JNJ\", \"WMT\"]\n",
                "WINDOWS = [\n",
                "    {\"name\": \"W1\", \"train\": (\"2020-01-01\", \"2021-06-30\"), \"test\": (\"2022-01-01\", \"2022-06-30\")},\n",
                "    {\"name\": \"W2\", \"train\": (\"2021-01-01\", \"2022-06-30\"), \"test\": (\"2023-01-01\", \"2023-06-30\")},\n",
                "    {\"name\": \"W3\", \"train\": (\"2022-01-01\", \"2023-06-30\"), \"test\": (\"2024-01-01\", \"2024-06-30\")},\n",
                "]\n",
                "INITIAL_CAPITAL = 1_000_000\n",
                "TRAIN_EPOCHS = 30\n",
                "print(f\"Tickers: {len(TICKERS)}, Windows: {len(WINDOWS)}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 3: Download Data + Feature Engineering (Combined)\n",
                "from stockstats import StockDataFrame\n",
                "\n",
                "print(\"Downloading data...\")\n",
                "df_list = []\n",
                "for tic in TICKERS:\n",
                "    try:\n",
                "        data = yf.download(tic, start=\"2020-01-01\", end=\"2024-12-31\", progress=False, auto_adjust=False)\n",
                "        if data.empty:\n",
                "            continue\n",
                "        if isinstance(data.columns, pd.MultiIndex):\n",
                "            data.columns = [col[0] for col in data.columns]\n",
                "        data = data.reset_index()\n",
                "        data['tic'] = tic\n",
                "        data = data.rename(columns={'Date': 'date', 'Open': 'open', 'High': 'high', 'Low': 'low', 'Close': 'close', 'Adj Close': 'adj_close', 'Volume': 'volume'})\n",
                "        if 'adj_close' not in data.columns:\n",
                "            data['adj_close'] = data['close']\n",
                "        data = data[['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'tic']]\n",
                "        df_list.append(data)\n",
                "        print(f\"  ✓ {tic}: {len(data)} rows\")\n",
                "    except Exception as e:\n",
                "        print(f\"  ✗ {tic}: {e}\")\n",
                "\n",
                "df = pd.concat(df_list, ignore_index=True)\n",
                "df['date'] = pd.to_datetime(df['date'])\n",
                "print(f\"\\nDownloaded: {len(df)} rows, {df['tic'].nunique()} tickers\")\n",
                "\n",
                "# Add technical indicators\n",
                "print(\"\\nAdding technical indicators...\")\n",
                "result = []\n",
                "for tic in df['tic'].unique():\n",
                "    tic_df = df[df['tic'] == tic].copy().sort_values('date').reset_index(drop=True)\n",
                "    stock = StockDataFrame.retype(tic_df[['date', 'open', 'high', 'low', 'close', 'volume']].copy())\n",
                "    tic_df['macd'] = stock['macd'].values\n",
                "    tic_df['rsi_14'] = stock['rsi_14'].values\n",
                "    result.append(tic_df)\n",
                "\n",
                "df = pd.concat(result, ignore_index=True)\n",
                "df['macd'] = df.groupby('tic')['macd'].transform(lambda x: x.ffill().bfill())\n",
                "df['rsi_14'] = df.groupby('tic')['rsi_14'].transform(lambda x: x.ffill().bfill())\n",
                "df = df.dropna()\n",
                "print(f\"✅ Final dataset: {len(df)} rows\")\n",
                "df.head()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 4: Trading Environment\n",
                "class TradingEnv:\n",
                "    def __init__(self, df, initial_capital=1_000_000):\n",
                "        self.df = df.sort_values(['date', 'tic']).reset_index(drop=True)\n",
                "        self.dates = sorted(df['date'].unique())\n",
                "        self.tickers = sorted(df['tic'].unique())\n",
                "        self.n_stocks = len(self.tickers)\n",
                "        self.initial_capital = initial_capital\n",
                "        self.state_dim = 1 + self.n_stocks * 3  # cash + (price, macd, rsi) per stock\n",
                "        self.action_dim = self.n_stocks\n",
                "        \n",
                "    def reset(self):\n",
                "        self.day_idx = 0\n",
                "        self.cash = self.initial_capital\n",
                "        self.holdings = np.zeros(self.n_stocks)\n",
                "        self.portfolio_values = [self.initial_capital]\n",
                "        return self._get_state()\n",
                "    \n",
                "    def _get_state(self):\n",
                "        day = self.dates[self.day_idx]\n",
                "        day_data = self.df[self.df['date'] == day]\n",
                "        features = [self.cash / self.initial_capital]\n",
                "        prices = []\n",
                "        for tic in self.tickers:\n",
                "            row = day_data[day_data['tic'] == tic]\n",
                "            if len(row) > 0:\n",
                "                prices.append(row['close'].values[0])\n",
                "                features.extend([row['close'].values[0]/100, row['macd'].values[0], row['rsi_14'].values[0]/100])\n",
                "            else:\n",
                "                prices.append(0)\n",
                "                features.extend([0, 0, 0.5])\n",
                "        self.current_prices = np.array(prices)\n",
                "        return np.array(features, dtype=np.float32)\n",
                "    \n",
                "    def step(self, action):\n",
                "        action = np.clip(action, -1, 1)\n",
                "        pv_before = self.cash + np.sum(self.holdings * self.current_prices)\n",
                "        target = (action * 0.5 + 0.5) * pv_before / (self.current_prices + 1e-8)\n",
                "        self.holdings = target\n",
                "        self.cash = pv_before - np.sum(self.holdings * self.current_prices)\n",
                "        self.day_idx += 1\n",
                "        done = self.day_idx >= len(self.dates) - 1\n",
                "        state = self._get_state() if not done else np.zeros(self.state_dim)\n",
                "        pv_after = self.cash + np.sum(self.holdings * self.current_prices)\n",
                "        reward = (pv_after - pv_before) / pv_before\n",
                "        self.portfolio_values.append(pv_after)\n",
                "        return state, reward, done, {}\n",
                "\n",
                "print(\"✓ TradingEnv defined\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 5: Agent & Synapse Arbitrator\n",
                "class SimpleAgent:\n",
                "    def __init__(self, state_dim, action_dim):\n",
                "        self.net = nn.Sequential(\n",
                "            nn.Linear(state_dim, 64), nn.ReLU(),\n",
                "            nn.Linear(64, action_dim), nn.Tanh()\n",
                "        ).to(device)\n",
                "        self.opt = torch.optim.Adam(self.net.parameters(), lr=1e-3)\n",
                "        self.action_dim = action_dim\n",
                "        \n",
                "    def act(self, state):\n",
                "        with torch.no_grad():\n",
                "            return self.net(torch.FloatTensor(state).to(device)).cpu().numpy()\n",
                "    \n",
                "    def train_episode(self, env):\n",
                "        states, actions, rewards = [], [], []\n",
                "        state, done = env.reset(), False\n",
                "        while not done:\n",
                "            action = self.act(state) + np.random.normal(0, 0.1, self.action_dim)\n",
                "            action = np.clip(action, -1, 1)\n",
                "            next_state, reward, done, _ = env.step(action)\n",
                "            states.append(state); actions.append(action); rewards.append(reward)\n",
                "            state = next_state\n",
                "        # Simple policy gradient\n",
                "        returns = torch.FloatTensor([sum(rewards[i:]) for i in range(len(rewards))]).to(device)\n",
                "        returns = (returns - returns.mean()) / (returns.std() + 1e-8)\n",
                "        pred = self.net(torch.FloatTensor(states).to(device))\n",
                "        loss = -((pred * torch.FloatTensor(actions).to(device)).sum(1) * returns).mean()\n",
                "        self.opt.zero_grad(); loss.backward(); self.opt.step()\n",
                "        return sum(rewards)\n",
                "\n",
                "class SynapseArbitrator:\n",
                "    def __init__(self, agents, window=20):\n",
                "        self.agents = agents\n",
                "        self.profits = [[] for _ in agents]\n",
                "        self.window = window\n",
                "        \n",
                "    def predict(self, state):\n",
                "        scores = [np.mean(p[-self.window:]) if p else 0 for p in self.profits]\n",
                "        weights = softmax(np.array(scores))\n",
                "        actions = [a.act(state) for a in self.agents]\n",
                "        return sum(w * a for w, a in zip(weights, actions)), weights\n",
                "    \n",
                "    def update(self, reward):\n",
                "        for p in self.profits:\n",
                "            p.append(reward)\n",
                "\n",
                "print(\"✓ Agent & Arbitrator defined\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 6: Evaluation Helpers\n",
                "def slice_data(df, start, end):\n",
                "    return df[(df['date'] >= start) & (df['date'] <= end)].copy()\n",
                "\n",
                "def evaluate(agent, env):\n",
                "    state, done, rewards = env.reset(), False, []\n",
                "    while not done:\n",
                "        action = agent.act(state) if hasattr(agent, 'act') else agent.predict(state)[0]\n",
                "        state, reward, done, _ = env.step(action)\n",
                "        if hasattr(agent, 'update'): agent.update(reward)\n",
                "        rewards.append(reward)\n",
                "    sharpe = np.mean(rewards) / (np.std(rewards) + 1e-8) * np.sqrt(252)\n",
                "    total_return = (env.portfolio_values[-1] / env.portfolio_values[0] - 1) * 100\n",
                "    return {'sharpe': sharpe, 'return': total_return}\n",
                "\n",
                "print(\"✓ Helpers defined\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 7: Walk-Forward Experiment\n",
                "results = []\n",
                "\n",
                "for w in WINDOWS:\n",
                "    print(f\"\\n{'='*50}\")\n",
                "    print(f\"Window: {w['name']}\")\n",
                "    print(f\"{'='*50}\")\n",
                "    \n",
                "    train_df = slice_data(df, w['train'][0], w['train'][1])\n",
                "    test_df = slice_data(df, w['test'][0], w['test'][1])\n",
                "    \n",
                "    if len(train_df) < 100 or len(test_df) < 50:\n",
                "        print(f\"⚠ Skipping - insufficient data\")\n",
                "        continue\n",
                "    \n",
                "    train_env = TradingEnv(train_df, INITIAL_CAPITAL)\n",
                "    test_env = TradingEnv(test_df, INITIAL_CAPITAL)\n",
                "    \n",
                "    # Train 3 agents\n",
                "    print(\"Training agents...\")\n",
                "    agents = []\n",
                "    for i in range(3):\n",
                "        np.random.seed(42 + i*100)\n",
                "        torch.manual_seed(42 + i*100)\n",
                "        agent = SimpleAgent(train_env.state_dim, train_env.action_dim)\n",
                "        for ep in range(TRAIN_EPOCHS):\n",
                "            agent.train_episode(train_env)\n",
                "        agents.append(agent)\n",
                "        print(f\"  Agent {i+1} trained\")\n",
                "    \n",
                "    # Evaluate\n",
                "    print(\"Evaluating...\")\n",
                "    single = evaluate(agents[0], test_env)\n",
                "    synapse = evaluate(SynapseArbitrator(agents), test_env)\n",
                "    \n",
                "    results.append({\n",
                "        'window': w['name'],\n",
                "        'single_sharpe': round(single['sharpe'], 3),\n",
                "        'synapse_sharpe': round(synapse['sharpe'], 3),\n",
                "        'single_return': round(single['return'], 1),\n",
                "        'synapse_return': round(synapse['return'], 1),\n",
                "    })\n",
                "    \n",
                "    print(f\"  Single:  Sharpe={single['sharpe']:.3f}, Return={single['return']:.1f}%\")\n",
                "    print(f\"  Synapse: Sharpe={synapse['sharpe']:.3f}, Return={synapse['return']:.1f}%\")\n",
                "\n",
                "print(\"\\n\" + \"=\"*50)\n",
                "print(\"COMPLETE\")\n",
                "print(\"=\"*50)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 8: Results Summary\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "results_df = pd.DataFrame(results)\n",
                "print(results_df.to_string(index=False))\n",
                "\n",
                "print(f\"\\nAverage Single Sharpe:  {results_df['single_sharpe'].mean():.3f}\")\n",
                "print(f\"Average Synapse Sharpe: {results_df['synapse_sharpe'].mean():.3f}\")\n",
                "print(f\"Improvement: {results_df['synapse_sharpe'].mean() - results_df['single_sharpe'].mean():+.3f}\")\n",
                "\n",
                "# Plot\n",
                "fig, ax = plt.subplots(figsize=(10, 5))\n",
                "x = range(len(results_df))\n",
                "ax.bar([i-0.2 for i in x], results_df['single_sharpe'], 0.4, label='Single', color='gray')\n",
                "ax.bar([i+0.2 for i in x], results_df['synapse_sharpe'], 0.4, label='Synapse', color='green')\n",
                "ax.set_xticks(x); ax.set_xticklabels(results_df['window'])\n",
                "ax.set_ylabel('Sharpe Ratio'); ax.legend(); ax.axhline(0, color='red', linestyle='--', alpha=0.5)\n",
                "plt.title('Synapse vs Single Agent'); plt.tight_layout(); plt.show()\n",
                "\n",
                "results_df.to_csv('synapse_results.csv', index=False)\n",
                "print(\"\\n✅ Results saved to synapse_results.csv\")"
            ]
        }
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {"gpuType": "T4", "provenance": []},
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=4)

print("✅ Created simplified notebook with 8 cells")
print("   Cell 1: Setup")
print("   Cell 2: Configuration")
print("   Cell 3: Download + Features (COMBINED)")
print("   Cell 4: Trading Environment")
print("   Cell 5: Agent & Arbitrator")
print("   Cell 6: Evaluation Helpers")
print("   Cell 7: Walk-Forward Experiment")
print("   Cell 8: Results Summary")
