"""Stage 1 Validation: Can Chronos-2 forecast funding rate regime transitions?

Runs INSIDE the SAFFS Docker container (Python 3.11, chronos-forecasting 2.2.2).

Mount data + script:
    docker run --rm -it \
      -v /c/FinRL/FinRL-Pro_DS/data/crypto_cache:/app/data:ro \
      -v /c/FinRL/FinRL-Pro_DS/scripts/funding_arb_chronos_validation.py:/app/validate.py:ro \
      finrl-prism-api:latest python /app/validate.py

Tests:
1. Feed historical funding rates to Chronos-2 as context
2. Forecast 168 bars (1 week) ahead at each window boundary
3. Compare Chronos accuracy vs EMA-168h baseline
4. Specifically check: does Chronos predict W16→W17 funding collapse early?
"""

from __future__ import annotations

import logging
import sys
import time

import numpy as np
import pandas as pd
import torch

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# --- Config ---
ASSETS = ["ARB", "UNI", "LINK", "OP", "LTC", "FIL", "DOGE", "BTC", "ETH", "BNB"]
START_DATE = pd.Timestamp("2022-01-01", tz="UTC")
TRAIN_BARS = 8760
VAL_BARS = 720
TEST_BARS = 1440
STEP_BARS = 720

BORROW_COST_ANN = 8.33e-6 * 8760  # 0.073 = 7.3%
CONTEXT_LENGTH = 512  # Chronos context window
FORECAST_HORIZONS = [24, 72, 168]  # 1d, 3d, 7d ahead


def compute_window_test_range(w_idx: int) -> tuple[pd.Timestamp, pd.Timestamp]:
    test_start_offset = w_idx * STEP_BARS + TRAIN_BARS + VAL_BARS
    test_end_offset = test_start_offset + TEST_BARS - 1
    return (
        START_DATE + pd.Timedelta(hours=test_start_offset),
        START_DATE + pd.Timedelta(hours=test_end_offset),
    )


def load_chronos():
    """Load Chronos-2 pipeline."""
    try:
        from chronos import BaseChronosPipeline
    except ImportError:
        logger.error("chronos not installed. Run inside SAFFS Docker container.")
        sys.exit(1)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info(f"Loading Chronos-2 on {device}...")
    t0 = time.time()

    pipeline = BaseChronosPipeline.from_pretrained(
        "amazon/chronos-t5-small",  # Fast model for validation
        device_map=device,
        torch_dtype=torch.bfloat16,
    )
    logger.info(f"Chronos loaded in {time.time() - t0:.1f}s")
    return pipeline


def chronos_forecast(pipeline, context: np.ndarray, horizon: int) -> dict:
    """Run Chronos forecast on a 1D context series.

    Args:
        pipeline: Chronos pipeline
        context: 1D array of values (funding rates, already 0-centered)
        horizon: Number of steps to forecast

    Returns:
        dict with p10, p50, p90 arrays (each length=horizon)
    """
    # Chronos expects (batch, seq_len) — 2D tensor
    ctx = context[-CONTEXT_LENGTH:]
    ctx_tensor = torch.tensor(ctx, dtype=torch.float32).unsqueeze(0)  # (1, seq_len)

    quantiles, mean = pipeline.predict_quantiles(
        inputs=ctx_tensor,
        prediction_length=horizon,
        quantile_levels=[0.1, 0.5, 0.9],
    )

    # quantiles shape: (batch, horizon, n_quantiles) → (1, H, 3)
    q = quantiles[0].cpu().numpy()  # (H, 3)
    return {
        "p10": q[:, 0],  # 10th percentile, shape (H,)
        "p50": q[:, 1],  # median, shape (H,)
        "p90": q[:, 2],  # 90th percentile, shape (H,)
    }


def main():
    # Load pre-processed data (numpy: [epoch_seconds, annualized_rate])
    # Generated by: python -c "... np.save('data/crypto_cache/funding_mean_ann.npy', data)"
    npy_paths = [
        "/app/data/funding_mean_ann.npy",
        "data/crypto_cache/funding_mean_ann.npy",
    ]
    data = None
    for p in npy_paths:
        try:
            data = np.load(p)
            logger.info(f"Loaded funding data from {p}: shape={data.shape}")
            break
        except FileNotFoundError:
            continue

    if data is None:
        logger.error("Cannot find funding_mean_ann.npy")
        sys.exit(1)

    # Reconstruct series
    timestamps = pd.to_datetime(data[:, 0], unit="s", utc=True)
    mean_fr_ann = pd.Series(data[:, 1], index=timestamps, name="funding_rate_ann")

    logger.info(f"Funding series: {len(mean_fr_ann)} bars, "
                f"{mean_fr_ann.index.min()} → {mean_fr_ann.index.max()}")

    # EMA baseline
    ema_168 = mean_fr_ann.ewm(span=168, min_periods=24).mean()

    # Load Chronos
    pipeline = load_chronos()

    # --- Evaluation at window boundaries ---
    # For each test window start, forecast 1d/3d/7d ahead
    # Compare Chronos p50 vs EMA-168h vs actual

    eval_points = []
    for w_idx in range(15, 22):
        test_start, test_end = compute_window_test_range(w_idx)
        # Also evaluate at mid-window and before-window
        for offset_label, offset_days in [
            ("before", -30),
            ("start", 0),
            ("mid", 30),
        ]:
            eval_ts = test_start + pd.Timedelta(days=offset_days)
            if eval_ts in mean_fr_ann.index:
                eval_points.append((w_idx, offset_label, eval_ts))
            else:
                # Find nearest
                nearest = mean_fr_ann.index[mean_fr_ann.index.get_indexer([eval_ts], method="nearest")]
                if len(nearest) > 0:
                    eval_points.append((w_idx, offset_label, nearest[0]))

    print("\n" + "=" * 100)
    print("CHRONOS-2 FUNDING RATE FORECAST VALIDATION")
    print("=" * 100)

    results_by_horizon = {h: [] for h in FORECAST_HORIZONS}

    for w_idx, label, eval_ts in eval_points:
        # Get context (512 bars before eval point)
        ts_idx = mean_fr_ann.index.get_loc(eval_ts)
        if ts_idx < CONTEXT_LENGTH:
            continue

        context = mean_fr_ann.iloc[ts_idx - CONTEXT_LENGTH:ts_idx].values

        for horizon in FORECAST_HORIZONS:
            # Actual future values
            actual_end_idx = min(ts_idx + horizon, len(mean_fr_ann))
            if actual_end_idx <= ts_idx:
                continue
            actual = mean_fr_ann.iloc[ts_idx:actual_end_idx].values
            actual_mean = float(np.mean(actual))
            actual_above_borrow = actual_mean > BORROW_COST_ANN

            # EMA baseline forecast: current EMA value persists
            ema_forecast = float(ema_168.iloc[ts_idx])
            ema_above_borrow = ema_forecast > BORROW_COST_ANN

            # Chronos forecast
            try:
                fc = chronos_forecast(pipeline, context, horizon)
                chronos_p50 = float(np.mean(fc["p50"]))
                chronos_above_borrow = chronos_p50 > BORROW_COST_ANN
                chronos_p10 = float(np.mean(fc["p10"]))
                chronos_p90 = float(np.mean(fc["p90"]))
                spread = chronos_p90 - chronos_p10
            except Exception as e:
                logger.warning(f"Chronos failed at {eval_ts}: {e}")
                continue

            # Errors
            ema_error = abs(ema_forecast - actual_mean)
            chronos_error = abs(chronos_p50 - actual_mean)

            results_by_horizon[horizon].append({
                "window": w_idx,
                "label": label,
                "eval_ts": eval_ts,
                "actual_mean": actual_mean,
                "actual_above": actual_above_borrow,
                "ema_forecast": ema_forecast,
                "ema_above": ema_above_borrow,
                "ema_error": ema_error,
                "ema_correct": ema_above_borrow == actual_above_borrow,
                "chronos_p50": chronos_p50,
                "chronos_above": chronos_above_borrow,
                "chronos_error": chronos_error,
                "chronos_correct": chronos_above_borrow == actual_above_borrow,
                "chronos_spread": spread,
            })

    # --- Print results ---
    for horizon in FORECAST_HORIZONS:
        results = results_by_horizon[horizon]
        if not results:
            continue

        days = horizon / 24
        print(f"\n{'='*100}")
        print(f"HORIZON: {horizon}h ({days:.0f}d) — {len(results)} evaluation points")
        print(f"{'='*100}")

        print(f"\n  {'Win':>3} {'Where':>7} | {'Actual':>7} | {'EMA':>7} {'Err':>6} {'OK':>3} | "
              f"{'Chr p50':>7} {'Err':>6} {'OK':>3} | {'Spread':>7} | {'Winner':>7}")
        print("-" * 95)

        ema_correct = 0
        chr_correct = 0
        ema_better = 0
        chr_better = 0
        tie = 0

        for r in results:
            ema_ok = "Y" if r["ema_correct"] else "N"
            chr_ok = "Y" if r["chronos_correct"] else "N"
            if r["ema_correct"]:
                ema_correct += 1
            if r["chronos_correct"]:
                chr_correct += 1

            if r["chronos_error"] < r["ema_error"]:
                winner = "Chronos"
                chr_better += 1
            elif r["ema_error"] < r["chronos_error"]:
                winner = "EMA"
                ema_better += 1
            else:
                winner = "Tie"
                tie += 1

            print(f"  W{r['window']:2d} {r['label']:>7} | "
                  f"{r['actual_mean']*100:6.1f}% | "
                  f"{r['ema_forecast']*100:6.1f}% {r['ema_error']*100:5.1f}% {ema_ok:>3} | "
                  f"{r['chronos_p50']*100:6.1f}% {r['chronos_error']*100:5.1f}% {chr_ok:>3} | "
                  f"{r['chronos_spread']*100:6.1f}% | "
                  f"{winner:>7}")

        n = len(results)
        print(f"\n  Summary ({days:.0f}d horizon):")
        print(f"    EMA regime accuracy:     {ema_correct}/{n} ({ema_correct/n:.1%})")
        print(f"    Chronos regime accuracy:  {chr_correct}/{n} ({chr_correct/n:.1%})")
        print(f"    Chronos wins (lower MAE): {chr_better}/{n} ({chr_better/n:.1%})")
        print(f"    EMA wins (lower MAE):     {ema_better}/{n} ({ema_better/n:.1%})")

        # Key: transition accuracy (where EMA and actual DISAGREE)
        transitions = [r for r in results if r["ema_above"] != r["actual_above"]]
        if transitions:
            chr_catches = sum(1 for r in transitions if r["chronos_correct"])
            print(f"\n    TRANSITION POINTS (EMA wrong): {len(transitions)}")
            print(f"    Chronos catches transitions:   {chr_catches}/{len(transitions)}")

    # --- Overall verdict ---
    print(f"\n{'='*100}")
    print("OVERALL VERDICT")
    print(f"{'='*100}")

    all_results = []
    for h in FORECAST_HORIZONS:
        all_results.extend(results_by_horizon[h])

    if not all_results:
        print("  No results — check data paths")
        return

    total_ema_correct = sum(1 for r in all_results if r["ema_correct"])
    total_chr_correct = sum(1 for r in all_results if r["chronos_correct"])
    total_chr_better = sum(1 for r in all_results if r["chronos_error"] < r["ema_error"])
    n_total = len(all_results)

    all_transitions = [r for r in all_results if r["ema_above"] != r["actual_above"]]
    chr_catches_all = sum(1 for r in all_transitions if r["chronos_correct"])

    print(f"\n  Overall EMA accuracy:     {total_ema_correct}/{n_total} ({total_ema_correct/n_total:.1%})")
    print(f"  Overall Chronos accuracy: {total_chr_correct}/{n_total} ({total_chr_correct/n_total:.1%})")
    print(f"  Chronos lower MAE:        {total_chr_better}/{n_total} ({total_chr_better/n_total:.1%})")
    if all_transitions:
        print(f"  Transition points:        {len(all_transitions)}")
        print(f"  Chronos catches:          {chr_catches_all}/{len(all_transitions)} "
              f"({chr_catches_all/len(all_transitions):.1%})")

    if total_chr_correct > total_ema_correct and chr_catches_all > len(all_transitions) * 0.5:
        print("\n  >>> CHRONOS BEATS EMA: Proceed to Stage 2 (PRISM implementation) <<<")
    elif total_chr_correct >= total_ema_correct:
        print("\n  >>> CHRONOS MATCHES EMA: Marginal value. Consider simple EMA gate instead. <<<")
    else:
        print("\n  >>> CHRONOS WORSE THAN EMA: Use simple EMA gate (Option C). <<<")

    print("=" * 100)


if __name__ == "__main__":
    main()
