"""Generate Stage 2 (L1 multiseed), Stage 3 (walk-forward) and Stage 4 (recent-OOS)
configs for both gmgp1-spx500 variants from the Stage 1 HPO winners.

GENERATED, NOT HAND-WRITTEN, because the A/B only means anything while the two arms stay
byte-identical apart from `env.long_only`. Twelve configs maintained by hand would drift,
and a drifted knob would silently turn the comparison into a test of something else.

BUDGET CHANGES FROM STAGE 1, both deliberate:
  * total_timesteps 400K -> 1_200_000. Multiplicity (protocol v2 s3.5.1) is
    total_timesteps / bars_in_train_window; the 24-month window holds ~47.1K 15-min bars, so
    400K was ~8.5x -- explicitly sanctioned for HPO but UNDER-TRAINED for L1. 1.2M gives
    ~25.5x, mid the validated 15-40x productive zone. Do not carry the HPO budget forward.
  * hpo.enabled false, and the Stage 1 winning hyperparameters are baked in.

WALK-FORWARD WINDOWS are rolling 24-month train / ~5-month test, stepping forward through
the 2025-01+ reserve that HPO never saw. Fold 1's test window begins after the Stage 1 test
window ends, so no fold is scored on data used to select hyperparameters.

Usage:
    python scripts/gen_spx500_stage_configs.py --best C:/tmp/spx500_best_params.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]

# (train_start, train_end, test_start, test_end) — rolling 24mo train, ~5mo test.
WF_WINDOWS = [
    ("2023-01-03", "2024-12-31", "2025-01-02", "2025-05-30"),
    ("2023-06-01", "2025-05-30", "2025-06-02", "2025-10-31"),
    ("2023-11-01", "2025-10-31", "2025-11-03", "2026-03-31"),
    ("2024-04-01", "2026-03-31", "2026-04-01", "2026-08-14"),
]
RECENT_OOS = ("2024-06-17", "2026-06-15", "2026-06-16", "2026-08-14")

SAC_KEYS = {"lr_actor", "lr_critic", "lr_alpha", "tau", "gamma", "initial_alpha",
            "gradient_clip"}


def apply_best(cfg: dict, params: dict) -> dict:
    """Bake Stage 1 winners in. Routing mirrors run_full_pipeline's explicit map so a
    parameter cannot silently land in the wrong block."""
    for k, v in params.items():
        if k in SAC_KEYS:
            cfg["agents"]["sac"][k] = v
        elif k == "dsr_eta":
            cfg["env"]["reward"]["dsr_eta"] = v
        elif k == "deadband_threshold":
            cfg["env"]["deadband_threshold"] = v
        else:
            raise SystemExit(f"unrouted HPO param {k!r} — add a rule rather than guessing")
    return cfg


def write(cfg: dict, path: Path, header: str) -> None:
    path.write_text(header + yaml.safe_dump(cfg, sort_keys=False, width=100),
                    encoding="utf-8", newline="\n")
    print("wrote", path.relative_to(ROOT))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--best", required=True)
    ap.add_argument("--l1-steps", type=int, default=1_200_000)
    args = ap.parse_args()

    best = json.loads(Path(args.best).read_text(encoding="utf-8"))

    for tag, variant in (("ls", "long-short"), ("lo", "long-only")):
        base = yaml.safe_load(
            (ROOT / f"configs/gmgp1_spx500_{tag}_hpo.yaml").read_text(encoding="utf-8"))
        params = best[tag]["params"]
        trial_no = best[tag]["argmax_pf_trial"]
        prov = (f"# GENERATED by scripts/gen_spx500_stage_configs.py — DO NOT HAND-EDIT.\n"
                f"# Variant {variant}. Hyperparameters are Stage 1 study "
                f"gmgp1_spx500_{tag}_hpo_20260815 trial {trial_no} "
                f"(PF={best[tag]['pf']:.4f}, eval return={best[tag]['ret']:+.5f}).\n"
                f"# NOTE: trial {trial_no} is the argmax-PROFIT-FACTOR trial, which is what\n"
                f"# _select_best_trial falls back to because NO trial beat buy-and-hold. In this\n"
                f"# arm the argmax-RETURN trial was {best[tag]['argmax_ret_trial']} "
                f"(PF={best[tag]['argmax_ret_pf']:.4f}, return={best[tag]['argmax_ret_ret']:+.5f}).\n"
                f"# Selecting on the declared objective does NOT select the most profitable model.\n")

        # ---- Stage 2: L1 multiseed -------------------------------------------------
        cfg = apply_best(json.loads(json.dumps(base)), params)
        cfg["hpo"] = {"enabled": False}
        cfg["training"]["total_timesteps"] = args.l1_steps
        cfg["wandb"]["tags"] = [t for t in cfg["wandb"]["tags"] if t != "hpo"] + ["l1-multiseed"]
        write(cfg, ROOT / f"configs/gmgp1_spx500_{tag}_l1_multiseed.yaml",
              prov + f"# Stage 2 L1 multiseed. total_timesteps={args.l1_steps:,} => ~"
                     f"{args.l1_steps/47100:.1f}x multiplicity on the ~47.1K-bar train window\n"
                     f"# (protocol v2 productive zone 15-40x). Seeds supplied via --seed.\n\n")

        # ---- Stage 3: walk-forward folds -------------------------------------------
        for i, (trs, tre, tes, tee) in enumerate(WF_WINDOWS, 1):
            cfg = apply_best(json.loads(json.dumps(base)), params)
            cfg["hpo"] = {"enabled": False}
            cfg["training"]["total_timesteps"] = args.l1_steps
            cfg["data"].update(train_start_date=trs, train_end_date=tre,
                               val_start_date=tes, val_end_date=tee,
                               test_start_date=tes, test_end_date=tee)
            cfg["wandb"]["tags"] = [t for t in cfg["wandb"]["tags"] if t != "hpo"] + \
                                   ["walk-forward", f"wf-fold-{i}"]
            write(cfg, ROOT / f"configs/gmgp1_spx500_{tag}_wf_f{i}.yaml",
                  prov + f"# Stage 3 walk-forward fold {i}/4: train {trs}..{tre}, "
                         f"test {tes}..{tee}.\n# Every fold tests on the 2025-01+ reserve that "
                         f"Stage 1 HPO never saw.\n\n")

        # ---- Stage 4: recent OOS ----------------------------------------------------
        trs, tre, tes, tee = RECENT_OOS
        cfg = apply_best(json.loads(json.dumps(base)), params)
        cfg["hpo"] = {"enabled": False}
        cfg["training"]["total_timesteps"] = args.l1_steps
        cfg["data"].update(train_start_date=trs, train_end_date=tre,
                           val_start_date=tes, val_end_date=tee,
                           test_start_date=tes, test_end_date=tee)
        cfg["wandb"]["tags"] = [t for t in cfg["wandb"]["tags"] if t != "hpo"] + ["recent-oos"]
        write(cfg, ROOT / f"configs/gmgp1_spx500_{tag}_recent_oos.yaml",
              prov + f"# Stage 4 recent-OOS: train {trs}..{tre}, test {tes}..{tee} "
                     f"(the last ~60 days).\n\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
