"""Generate per-strategy Grafana dashboards from the fleet overview template.

Reads `docker/live/grafana/dashboards/trading_overview.json` and, for each
strategy in `docker/live/grafana/dashboards/strategies.yml`, emits a copy with
`{strategy="<name>"}` injected into every PromQL selector and a strategy-specific
title/uid. Outputs land in `docker/live/grafana/dashboards/strategies/` and are
committed to the repo — Dockerfile.grafana just COPYs the whole dashboards dir.

Re-run after editing the template or registry, then rebuild the grafana image.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
DASHBOARDS_DIR = REPO_ROOT / "docker" / "live" / "grafana" / "dashboards"
TEMPLATE = DASHBOARDS_DIR / "trading_overview.json"
REGISTRY = DASHBOARDS_DIR.parent / "strategies.yml"
OUT_DIR = DASHBOARDS_DIR / "strategies"

GEN_MARKER = "generated by scripts/generate_grafana_dashboards.py -- do not edit"

# Matches a metric name optionally followed by an existing label selector.
# Group 1: metric name (finrl_*). Group 2: existing selector body (without braces) or None.
METRIC_RE = re.compile(r"\b(finrl_[a-zA-Z0-9_]+)(?:\{([^}]*)\})?")


def inject_strategy(expr: str, strategy: str) -> str:
    def repl(m: re.Match[str]) -> str:
        metric, existing = m.group(1), m.group(2)
        label = f'strategy="{strategy}"'
        if existing is None or not existing.strip():
            return f"{metric}{{{label}}}"
        # Merge: drop any pre-existing strategy=... then prepend ours.
        parts = [p.strip() for p in existing.split(",") if p.strip() and not p.strip().startswith("strategy=")]
        parts.insert(0, label)
        return f"{metric}{{{', '.join(parts)}}}"
    return METRIC_RE.sub(repl, expr)


def build_dashboard(template: dict, strategy: str, uid: str) -> dict:
    dash = copy.deepcopy(template)
    dash["title"] = strategy
    dash["uid"] = uid
    dash["description"] = GEN_MARKER
    tags = list(dash.get("tags", []))
    if strategy not in tags:
        tags.append(strategy)
    dash["tags"] = tags
    for panel in dash.get("panels", []):
        for target in panel.get("targets", []):
            if "expr" in target:
                target["expr"] = inject_strategy(target["expr"], strategy)
            # Single-series now — drop the multi-strategy legend format.
            if target.get("legendFormat") == "{{strategy}}":
                target.pop("legendFormat", None)
    return dash


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true", help="Print plan without writing files.")
    args = ap.parse_args()

    template = json.loads(TEMPLATE.read_text(encoding="utf-8"))
    registry = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    strategies = registry.get("strategies") or []
    if not strategies:
        print(f"No strategies in {REGISTRY}", file=sys.stderr)
        return 1

    if not args.dry_run:
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        # Wipe any stale generated files (strategy removed from registry).
        for stale in OUT_DIR.glob("*.json"):
            stale.unlink()

    for entry in strategies:
        name = entry["name"]
        uid = entry["uid"]
        dash = build_dashboard(template, name, uid)
        out_file = OUT_DIR / f"{name.replace('-', '_')}.json"
        if args.dry_run:
            sample = dash["panels"][0]["targets"][0]["expr"]
            print(f"[dry-run] {out_file.relative_to(REPO_ROOT)}  sample expr: {sample}")
        else:
            out_file.write_text(json.dumps(dash, indent=2) + "\n", encoding="utf-8")
            print(f"wrote {out_file.relative_to(REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
