"""Does the intraday substrate's base book turn the funnel into a false-positive factory? (cont-151)

THE HAZARD. Crucible's corrected contract promotes on MARGINAL uplift: ΔSR of (base + candidate) over
base, plus a Sharpe-difference z. That is sound only while the base book is a fair comparator. The
intraday substrate's base book is not obviously one:

    intraday TSMOM, hold 21 bars, 2 bps one-way   ->  calendar SR  -0.78
    ... the same book frictionless                ->  calendar SR  -0.15   (i.e. trend is NOISE here)
    ... annual cost drag                          ->  30.6% of notional

So the base loses, and almost all of the loss is friction. Blending ANY lower-turnover stream into a
book that bleeds 30%/yr raises the combined Sharpe — the candidate would be rewarded for TRADING
LESS, not for predicting anything. If that mechanism passes the gates, then the first PROMISING
verdicts this system has ever produced would be artifacts of the baseline, and they would arrive on
the one substrate built specially to be mineable.

THE TEST. Score ZERO-ALPHA candidates through the SHIPPED scorer
(``corrected_contract.corrected_contract_fitness``) against the REAL intraday base book. The
candidates are gross-1 dollar-neutral random books net of the same cost the miner charges — the exact
shape a genuine candidate has, with the alpha removed. Under a fair baseline the pass rate should sit
near the contract's nominal FPR (t_min 2.33 one-sided ~ 1%).

PRE-REGISTERED READING (written before running):
  * pass rate <= ~2%  -> baseline is fair; the ΔSR gate is measuring prediction; MINE.
  * pass rate >> 2%   -> the base book manufactures uplift; any PROMISING from this substrate is
                         uninterpretable and the substrate must NOT be mined against this book.

The null candidates are generated by the same rank-L/S mechanism the DSL uses, driven by random
scores, so turnover and gross are realistic rather than idealized; a null built as an iid return
stream would understate its own trading cost and quietly make the dilution effect look smaller.

Usage:
    python scripts/research/crucible_intraday_null_calibration.py [--n-null 200]
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from finrl_pro_ds.crucible.corrected_contract import (  # noqa: E402
    CorrectedConfig,
    corrected_contract_fitness,
    fresh_lord_level,
)
from finrl_pro_ds.crucible.data.intraday_panel import (  # noqa: E402
    build_fx_majors_panel,
    build_intraday_panel,
)
from finrl_pro_ds.signals.eval_harness import _ann_sharpe, _ls_weights  # noqa: E402
from finrl_pro_ds.signals.generation.base_sleeves import (  # noqa: E402
    _book_from_target_weights,
    intraday_base_sleeves,
)
from finrl_pro_ds.signals.generation.config import (  # noqa: E402
    load_generation_config,
    load_generation_meta,
)


def _null_candidate(panel, rng, *, hold_horizon: int, cost_bps: float,
                    ls_min_names: int) -> np.ndarray:
    """A gross-1 dollar-neutral rank-L/S book driven by RANDOM scores, net of cost.

    Same book mechanics as a real candidate (``_ls_weights`` + the shared booking loop), so it pays
    realistic turnover. Scores are a random walk per name rather than iid noise: an iid score would
    re-randomize the ranking every bar, giving maximal turnover and an unrealistically harsh null.
    """
    scores = np.cumsum(rng.standard_normal((panel.T, len(panel.tickers))), axis=0)
    w = np.zeros((panel.T, len(panel.tickers)))
    for t in range(panel.T):
        w[t] = _ls_weights(scores[t], panel.active[t], min_names=ls_min_names)
    return np.asarray(_book_from_target_weights(
        w, panel.forward_returns(1), hold_horizon=hold_horizon, cost_bps=cost_bps))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-null", type=int, default=200)
    ap.add_argument("--base-hold", type=int, default=None,
                    help="override the base book's rebalance cadence (bars); default = config")
    ap.add_argument("--config", default="configs/intraday_signal_eval.gates.yaml")
    ap.add_argument("--panel", choices=("intraday", "intraday_fx"), default=None,
                    help="override the panel builder; default follows the config's generation.panel")
    ap.add_argument("--corrected-config", default="configs/crucible_corrected_contract.gates.yaml")
    ap.add_argument("--out", default="results/crucible_power_units/intraday_null_calibration.json")
    args = ap.parse_args()
    logging.disable(logging.INFO)

    cfg, ek = load_generation_config(ROOT / args.config)
    meta = load_generation_meta(ROOT / args.config)
    cc = CorrectedConfig.from_yaml(ROOT / args.corrected_config)
    lord = fresh_lord_level(cc)
    which = args.panel or meta["panel"]
    panel = build_fx_majors_panel() if which == "intraday_fx" else build_intraday_panel()
    ppy = float(cfg.periods_per_year)

    # Mirror the runner EXACTLY: the base book uses its own cadence, the candidate uses hold_horizon.
    # --base-hold overrides it so the pre-fix baseline can be re-measured for comparison.
    base_hold = args.base_hold or meta.get("base_hold_horizon") or ek["hold_horizon"]
    base, _comps = intraday_base_sleeves(
        panel, hold_horizon=int(base_hold), cost_bps=ek["cost_bps"],
        periods_per_year=ppy, verify_causal=True, return_components=True)
    ts = panel.dates.astype("datetime64[s]").astype(np.int64).astype(np.float64)
    b = base["tsmom"]
    print(f"base book: calendar SR {_ann_sharpe(b[np.isfinite(b)], ppy):+.4f}  "
          f"(base hold {base_hold} bars, candidate hold {ek['hold_horizon']} bars, "
          f"{ek['cost_bps'] * 1e4:.0f} bp)")
    print(f"contract: t_min {cc.t_min}, lord level {lord:.5f}, uplift_min "
          f"{cfg.min_combination_uplift}\n")

    rows = []
    rng = np.random.default_rng(20260802)
    for i in range(args.n_null):
        cand = _null_candidate(panel, rng, hold_horizon=ek["hold_horizon"],
                               cost_bps=ek["cost_bps"], ls_min_names=ek["ls_min_names"])
        res = corrected_contract_fitness(cand, base, ts, cfg, cc, lord_level=lord)
        fin = cand[np.isfinite(cand)]
        rows.append({
            "standalone_sr": float(_ann_sharpe(fin, ppy)),
            "delta_sr": float(res.delta_sr), "z": float(res.corrected_t),
            "p": float(res.p_value), "passes": bool(res.passes_corrected),
            "t_pass": bool(res.t_pass), "lord_pass": bool(res.lord_pass),
            "uplift_pass": bool(res.uplift_pass), "fragility_pass": bool(res.fragility_pass),
            "collinearity_pass": bool(res.collinearity_pass),
        })
        if (i + 1) % 25 == 0:
            pr = sum(r["passes"] for r in rows) / len(rows)
            print(f"  {i + 1:>4}/{args.n_null} nulls  pass rate {pr:.1%}")

    n = len(rows)
    n_pass = sum(r["passes"] for r in rows)
    z = np.array([r["z"] for r in rows])
    d = np.array([r["delta_sr"] for r in rows])
    s = np.array([r["standalone_sr"] for r in rows])
    verdict = {
        "n_null": n, "pass_rate": n_pass / n,
        "z_median": float(np.nanmedian(z)), "z_frac_over_t_min": float(np.mean(z >= cc.t_min)),
        "delta_sr_median": float(np.nanmedian(d)),
        "delta_sr_frac_over_uplift_min": float(np.mean(d >= cfg.min_combination_uplift)),
        "standalone_sr_median": float(np.nanmedian(s)),
        "base_sr_calendar": float(_ann_sharpe(b[np.isfinite(b)], ppy)),
        "base_hold_horizon": int(base_hold), "candidate_hold_horizon": int(ek["hold_horizon"]),
        "periods_per_year": ppy, "t_min": cc.t_min,
        "uplift_min": float(cfg.min_combination_uplift),
        # Per-leg pass rates: WHICH guard (if any) is actually holding the null back. A gate that is
        # 100% on the nulls is contributing nothing on this substrate.
        "leg_pass_rates": {leg: float(np.mean([r[leg] for r in rows])) for leg in
                           ("t_pass", "lord_pass", "uplift_pass", "fragility_pass",
                            "collinearity_pass")},
    }
    print(f"\n{'=' * 62}\nZERO-ALPHA NULLS, n={n}")
    print(f"  standalone SR   median {verdict['standalone_sr_median']:+.4f}  (should be ~0)")
    print(f"  marginal ΔSR    median {verdict['delta_sr_median']:+.4f}   "
          f"frac >= uplift_min {verdict['delta_sr_frac_over_uplift_min']:.1%}")
    print(f"  Sharpe-diff z   median {verdict['z_median']:+.3f}    "
          f"frac >= t_min {verdict['z_frac_over_t_min']:.1%}")
    print(f"  FULL-GATE PASS RATE {verdict['pass_rate']:.1%}   (nominal ~1%)")
    print("  per-leg pass rates on the nulls (1.0 = leg contributes nothing here):")
    for leg, rate in verdict["leg_pass_rates"].items():
        print(f"      {leg:<20}{rate:.1%}")
    out = ROOT / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({**verdict, "rows": rows}, indent=2), encoding="utf-8")
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
